# Deep Learning A Z Boltzmann Machines - Recomendação

- Documentação: https://github.com/echen/restricted-boltzmann-machines

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import rbm

In [ ]:
rbm = rbm.RBM(num_visible = 6, num_hidden = 2)

In [ ]:
base = np.array([[1, 1, 1, 0, 0, 0],
                 [1, 0, 1, 0, 0, 0],
                 [1, 1, 1, 0, 0, 0],
                 [0, 0, 1, 1, 1, 1],
                 [0, 0, 1, 1, 0, 1],
                 [0, 0, 1, 1, 0, 1]])

In [ ]:
base.shape

(6, 6)

In [ ]:
filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

In [ ]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 9.070682439663578
Epoch 1: error is 8.903237625622893
Epoch 2: error is 8.74815109875171
Epoch 3: error is 8.586987677667416
Epoch 4: error is 8.471709201386936
Epoch 5: error is 8.399336218191563
Epoch 6: error is 8.178467455898993
Epoch 7: error is 8.120128795103016
Epoch 8: error is 8.124793805695905
Epoch 9: error is 7.942372182828603
Epoch 10: error is 7.893949305225595
Epoch 11: error is 7.834982860506668
Epoch 12: error is 7.765532851006974
Epoch 13: error is 7.646646948650793
Epoch 14: error is 7.381965610790909
Epoch 15: error is 7.54519194284307
Epoch 16: error is 7.573749710050024
Epoch 17: error is 7.485045111535844
Epoch 18: error is 7.226096581689905
Epoch 19: error is 7.12443059601943
Epoch 20: error is 7.329523115901396
Epoch 21: error is 7.316721378166176
Epoch 22: error is 7.156573458256976
Epoch 23: error is 7.236397422364561
Epoch 24: error is 7.0445691751808335
Epoch 25: error is 7.530383280622499
Epoch 26: error is 7.179129855780232
Epoch 27: err

In [ ]:
rbm.weights, rbm.weights.shape

(array([[ 2.48103265,  2.35083648,  0.42117782],
        [-1.02972013, -3.27639619,  7.9340733 ],
        [ 0.2186984 , -7.24970436,  3.34812616],
        [ 4.95015819,  3.92624338,  1.91190678],
        [ 0.94144441,  3.62634265, -8.2221572 ],
        [-1.31700295,  0.61195931, -4.54943646],
        [ 0.94661353,  3.6223964 , -8.22474331]]),
 (7, 3))

In [ ]:
usuario1 = np.array([[1, 1, 0, 1, 0, 0]])
usuario2 = np.array([[0, 0, 0, 1, 1, 0]])

In [ ]:
filmes

['A bruxa',
 'Invocação do mal',
 'O chamado',
 'Se beber não case',
 'Gente grande',
 'American pie']

In [ ]:
rbm.run_visible(usuario1)

array([[0., 1.]])

In [ ]:
rbm.run_visible(usuario2)

array([[1., 0.]])

In [ ]:
camada_escondida = np.array([[0, 1]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[1., 1., 1., 0., 0., 0.]])

In [ ]:
len(usuario1[0]), usuario1.shape

(6, (1, 6))

In [ ]:
for i in range(len(usuario1[0])):
  if usuario1[0, i] == 0 and recomendacao[0, i] == 1:
    print(filmes[i])

O chamado
