# Deep Learning A Z Autoencoder classificação

In [ ]:
!pip install tensorflow==2.16.1

In [ ]:
import tensorflow as tf
import keras
import numpy as np

In [ ]:
tf.__version__, keras.__version__, np.__version__

('2.16.1', '3.4.1', '1.26.4')

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import InputLayer, Input, Dense
from tensorflow.keras import utils as np_utils

In [ ]:
(X_treinamento, y_treinamento), (X_teste, y_teste) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_treinamento = X_treinamento.astype('float32') / 255
X_teste = X_teste.astype('float32') / 255

In [ ]:
X_treinamento[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [ ]:
y_treinamento

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
y_treinamento = np_utils.to_categorical(y_treinamento)
y_teste = np_utils.to_categorical(y_teste)

In [ ]:
y_treinamento, y_treinamento[0]

(array([[0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]))

In [ ]:
X_treinamento.shape

(60000, 28, 28)

In [ ]:
X_treinamento = X_treinamento.reshape((len(X_treinamento), np.prod(X_treinamento.shape[1:])))
X_teste = X_teste.reshape((len(X_teste), np.prod(X_teste.shape[1:])))

In [ ]:
X_treinamento.shape, X_teste.shape

((60000, 784), (10000, 784))

In [ ]:
# 784 -> 32 -> 784
autoencoder = Sequential()
autoencoder.add(InputLayer(shape = (784,)))
autoencoder.add(Dense(units = 32, activation = 'relu'))
autoencoder.add(Dense(units = 784, activation = 'sigmoid'))
autoencoder.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │          25,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 784)                 │          25,872 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 50,992 (199.19 KB)

 Trainable params: 50,992 (199.19 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
autoencoder.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
autoencoder.fit(X_treinamento, X_treinamento, epochs = 50,
                batch_size=256, validation_data=(X_teste, X_teste))

Epoch 1/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.0133 - loss: 0.3849 - val_accuracy: 0.0085 - val_loss: 0.1886
Epoch 2/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.0102 - loss: 0.1794 - val_accuracy: 0.0118 - val_loss: 0.1537
Epoch 3/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.0103 - loss: 0.1496 - val_accuracy: 0.0099 - val_loss: 0.1339
Epoch 4/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.0101 - loss: 0.1319 - val_accuracy: 0.0099 - val_loss: 0.1216
Epoch 5/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0103 - loss: 0.1206 - val_accuracy: 0.0103 - val_loss: 0.1132
Epoch 6/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.0105 - loss: 0.1131 - val_accuracy: 0.0114 - val_loss: 0.1075
Epoch 7/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.0115 - loss: 0.1073 - val_accuracy: 0.0115 - val_loss: 0.1036
Epoch 8/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0116 - loss: 0.1039 - val_accu

In [ ]:
autoencoder.layers

[<Dense name=dense, built=True>, <Dense name=dense_1, built=True>]

In [ ]:
dimensao_original = Input(shape=(784,))
camada_encoder = autoencoder.layers[0]
encoder = Model(dimensao_original, camada_encoder(dimensao_original))

In [ ]:
treinamento_codificado = encoder.predict(X_treinamento)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step


In [ ]:
teste_codificado = encoder.predict(X_teste)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [ ]:
treinamento_codificado.shape, teste_codificado.shape

((60000, 32), (10000, 32))

- Sem redução de dimensionalidade

In [ ]:
(784 + 10) / 2

397.0

In [ ]:
X_treinamento.shape, X_teste.shape

((60000, 784), (10000, 784))

In [ ]:
# 784 -> 397 -> 397 -> 10
c1 = Sequential()
c1.add(InputLayer(shape = (784,)))
c1.add(Dense(units = 397, activation='relu'))
c1.add(Dense(units = 397, activation='relu'))
c1.add(Dense(units = 10, activation='softmax'))

c1.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

c1.fit(X_treinamento, y_treinamento, batch_size=256, epochs = 100,
       validation_data=(X_teste, y_teste))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step - accuracy: 0.8530 - loss: 0.5211 - val_accuracy: 0.9652 - val_loss: 0.1158
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 10s 25ms/step - accuracy: 0.9682 - loss: 0.1064 - val_accuracy: 0.9741 - val_loss: 0.0860
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 9s 19ms/step - accuracy: 0.9796 - loss: 0.0646 - val_accuracy: 0.9787 - val_loss: 0.0684
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - accuracy: 0.9870 - loss: 0.0438 - val_accuracy: 0.9791 - val_loss: 0.0687
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 9s 19ms/step - accuracy: 0.9910 - loss: 0.0284 - val_accuracy: 0.9800 - val_loss: 0.0666
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - accuracy: 0.9939 - loss: 0.0200 - val_accuracy: 0.9800 - val_loss: 0.0674
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - accuracy: 0.9954 - loss: 0.0160 - val_accuracy: 0.9787 - val_loss: 0.0761
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - accuracy: 0.9965 - loss: 0.0122 

- Com redução de dimensionalidade

In [ ]:
(32 + 10) / 2

21.0

In [ ]:
treinamento_codificado.shape, teste_codificado.shape

((60000, 32), (10000, 32))

In [ ]:
# 32 -> 397 -> 397 -> 10
c1 = Sequential()
c1.add(InputLayer(shape = (32,)))
c1.add(Dense(units = 21, activation='relu'))
c1.add(Dense(units = 21, activation='relu'))
c1.add(Dense(units = 10, activation='softmax'))

c1.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

c1.fit(treinamento_codificado, y_treinamento, batch_size=256, epochs = 100,
       validation_data=(teste_codificado, y_teste))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2788 - loss: 2.3628 - val_accuracy: 0.7632 - val_loss: 0.7308
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7903 - loss: 0.6629 - val_accuracy: 0.8567 - val_loss: 0.4636
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8603 - loss: 0.4600 - val_accuracy: 0.8812 - val_loss: 0.3864
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8820 - loss: 0.3930 - val_accuracy: 0.8936 - val_loss: 0.3527
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8912 - loss: 0.3660 - val_accuracy: 0.8937 - val_loss: 0.3499
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8998 - loss: 0.3415 - val_accuracy: 0.9056 - val_loss: 0.3102
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9020 - loss: 0.3291 - val_accuracy: 0.9107 - val_loss: 0.3007
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9093 - loss: 0.3034 - val_accu