# Deep Learning A Z Classificação Binária - Classificar um registro

In [ ]:
!pip install tensorflow==2.16.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 57.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 39.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 55.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 32.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 20.9 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Successfully uninstalled h5py-3.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.15.2
    Uninstalling tensorboard-2.15.2:
      Successfully uninstalled tensorboard-2.15.2
  Attempting uninstall: keras
    Fo

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
pd.__version__, np.__version__, tf.__version__

('2.0.3', '1.25.2', '2.16.1')

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [ ]:
X = pd.read_csv('entradas_breast.csv')
y = pd.read_csv('saidas_breast.csv')

In [ ]:
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid'))

In [ ]:
classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [ ]:
classificador.fit(X, y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - binary_accuracy: 0.5390 - loss: 1.8210
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6568 - loss: 0.6649
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6825 - loss: 0.5558
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7509 - loss: 0.5350
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8001 - loss: 0.4737
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8141 - loss: 0.4219
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8417 - loss: 0.4027
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8151 - loss: 0.3753
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8361 - loss: 0.3792
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8464 - loss: 0.3447
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8922 -

In [ ]:
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [ ]:
novo = np.array([[ 15.80,  8.34,   118,   900,  0.10,  0.26,  0.08, 0.134, 0.178,  0.20,
                    0.05,  1098,  0.87,  4500, 145.2, 0.005,  0.04,  0.05, 0.015,  0.03,
                   0.007, 23.15, 16.64, 178.5,  2018,  0.14, 0.185,  0.84,   158, 0.363]])

In [ ]:
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [ ]:
novo.size, novo.shape

(30, (1, 30))

In [ ]:
previsao = classificador.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


In [ ]:
previsao

array([[1.]], dtype=float32)

In [ ]:
previsao = previsao > 0.5
print(previsao)

[[ True]]


In [ ]:
if previsao:
  print('Malígno')
else:
  print('Benigno')

Malígno


In [ ]:
classificador.save('classificador_breast.keras')

In [ ]:
classificador_novo = tf.keras.models.load_model('/content/classificador_breast.keras')

In [ ]:
classificador_novo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,572 (6.14 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 787 (3.08 KB)

In [ ]:
classificador_novo.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[1.]], dtype=float32)