# Deep Learning A Z Classificação binária - Brest Cancer simples

- Base de dados: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.0.3'

In [ ]:
# previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [ ]:
# classe
y = pd.read_csv('/content/saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
sklearn.__version__

'1.2.2'

In [ ]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [ ]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [ ]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [ ]:
#!pip install tensorflow==2.16.1

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [ ]:
tf.__version__

'2.16.1'

In [ ]:
(30 + 1) / 2

15.5

In [ ]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

In [ ]:
30 * 16, 496 - 480 # Bias

(480, 16)

In [ ]:
496 + 17

513

In [ ]:
rede_neural.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
426 / 10

42.6

In [ ]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)

In [ ]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [ ]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6522 - loss: 1.3415
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7238 - loss: 0.5342
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7201 - loss: 0.5117
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7511 - loss: 0.4931
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7793 - loss: 0.4401
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7778 - loss: 0.4861
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8152 - loss: 0.3813
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8109 - loss: 0.4430
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8551 - loss: 0.5308
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8445 - loss: 0.4198
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8343 -

In [ ]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-1.41127519e-02, -4.52280715e-02,  4.42318648e-01,
          1.04644917e-01, -3.52899641e-01, -2.17594430e-01,
         -8.57435241e-02,  5.20044565e-02,  1.11205667e-01,
          1.19060531e-01,  3.34865265e-02, -1.71077669e-01,
          2.81596571e-01, -1.48560971e-01, -4.10162285e-03,
         -1.79043785e-01],
        [ 3.38910185e-02, -1.59747154e-02,  3.55228305e-01,
          7.95797557e-02, -2.60388702e-01, -1.25997499e-01,
         -2.67973721e-01, -2.69585084e-02,  1.21370226e-01,
          1.33738503e-01,  1.15423473e-02, -8.41617882e-02,
          3.22641194e-01, -1.06361724e-01, -2.15935111e-02,
         -1.92745268e-01],
        [ 7.92124495e-03,  3.80868390e-02,  1.10691682e-01,
          9.21853781e-02, -1.43219292e-01, -1.44911930e-01,
         -1.31102026e-01, -4.01261635e-03, -3.90398018e-02,
         -8.89754519e-02,  2.14140378e-02, -3.91630344e-02,
          1.98972344e-01, -1.28346652e-01, -8.61601457e-02,
         -3.81902829e-02],
        [-5.2972670

In [ ]:
len(pesos0)

2

In [ ]:
len(pesos0[1])

16

In [ ]:
len(pesos0[0])

30

In [ ]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-0.04888751,  0.02027647, -0.04414139,  0.01271023,  0.03858504,
          0.01551524,  0.02871505,  0.01399572, -0.00261278,  0.0357602 ,
          0.0324954 , -0.04077858, -0.01453006, -0.04977283,  0.00552082,
         -0.02270651],
        [ 0.03227206,  0.03674269, -0.02122471,  0.03147934, -0.03910389,
          0.01175678, -0.01140225,  0.01240904, -0.04056536, -0.02825404,
         -0.01544416, -0.01921512, -0.00824895, -0.04269169,  0.04964013,
          0.00234523],
        [ 0.45570415, -0.09219041,  0.0782887 , -0.29287887, -0.0537976 ,
         -0.01971023, -0.01525183, -0.0625585 , -0.31552953,  0.330548  ,
         -0.18345135, -0.2611442 ,  0.22646087, -0.35200152,  0.05011507,
         -0.01903803],
        [ 0.15764682, -0.10545875, -0.01777106, -0.07308979, -0.02316022,
         -0.04998973, -0.03534211,  0.02987989, -0.08462939,  0.02603833,
         -0.08951166, -0.1650642 ,  0.04654586, -0.11869752, -0.03830993,
         -0.02866403],
        [ 0.15593456

In [ ]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.29821962],
        [ 0.18120265],
        [-0.19840898],
        [ 0.06017094],
        [ 0.01229232],
        [-0.33766204],
        [-0.3126552 ],
        [ 0.04301826],
        [ 0.08909699],
        [ 0.21952067],
        [ 0.1199372 ],
        [ 0.13295366],
        [ 0.19531427],
        [ 0.4205427 ],
        [-0.27592668],
        [-0.19958387]], dtype=float32),
 array([0.28654853], dtype=float32)]

In [ ]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [ ]:
previsoes

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [

In [ ]:
y_teste

0
289  1
511  1
285  1
473  1
350  1
..  ..
416  1
219  0
11   0
486  1
271  1

[143 rows x 1 columns]

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
accuracy_score(y_teste, previsoes)

0.8951048951048951

In [ ]:
confusion_matrix(y_teste, previsoes)

array([[48,  6],
       [ 9, 80]])

In [ ]:
48 + 80, 9 + 6

(128, 15)

In [ ]:
128 / 143, 15 / 143

(0.8951048951048951, 0.1048951048951049)

In [ ]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7901 - loss: 2.1767  


[1.6290218830108643, 0.8181818127632141]